In [1]:
import pandas as pd
path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv"

df = pd.read_csv(path, sep=";", low_memory=False)

df.head(10)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,blackcarbon,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude
0,0,2019-01-22 19:34:01,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.895156,360,24.406454,64.666350
1,0,2019-01-22 23:30:01,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.024534,370,24.406467,64.666350
2,0,2019-01-22 00:12:21,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1342.213400,370,24.277414,64.648370
3,0,2019-01-22 21:35:11,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.982116,680,24.406456,64.666360
4,0,2019-01-22 10:10:12,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.404294,730,24.406460,64.666370
5,0,2019-01-22 14:01:21,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.364585,360,24.406422,64.666336
6,0,2019-01-22 22:46:30,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.563094,420,24.406427,64.666340
7,0,2019-01-22 10:34:31,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.441745,379,24.406462,64.666370
8,0,2019-01-22 22:53:30,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.751318,361,24.406427,64.666350
9,0,2019-01-22 06:38:31,NaN,NaN,Unknown,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.126188,1080,24.406458,64.666350

In [6]:
import track_builder as tb

files = [r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv",
         r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201902.csv"]

df = tb.load_astd_data(files)

df.head(5)

Loading ASTD CSVs:   0%|          | 0/2 [00:00<?, ?it/s]

c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:96: DtypeWarning: Columns (3,5) have mixed types. Specify dtype option on import or set low_memory=False.

Loading ASTD CSVs:  50%|█████     | 1/2 [01:27<01:27, 87.79s/it]c:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:96: DtypeWarning: Columns (3,5) have mixed types. Specify dtype option on import or set low_memory=False.

Loading ASTD CSVs: 100%|██████████| 2/2 [02:24<00:00, 72.22s/it]

MemoryError: Unable to allocate 4.65 GiB for an array with shape (18, 34699682) and data type float64

In [4]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,fuelquality,fuelcons,co,co2,...,organiccarbon,oilbilgewater,blackwater,greywater,garbage,dist_nextpoint,sec_nextpoint,longitude,latitude,month
0,162,2019-01-01 00:00:00+00:00,iceland,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.242847,209,-21.827280,64.134210,2019-01
1,385,2019-01-01 00:00:00+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.987542,370,14.245747,67.389120,2019-01
2,3619,2019-01-01 00:00:00+00:00,norway,<NA>,other activities,1000 - 4999 gt,4,0.016730,0.000124,0.053035,...,1.017200e-05,2.720000e-08,0.001281,0.009481,0.0,491.440920,369,14.545295,68.205574,2019-01
3,1645,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,< 1000 gt,0,0.001227,0.000009,0.003890,...,7.460000e-07,6.400000e-09,0.001170,0.003844,0.0,0.731465,361,-23.703033,64.896220,2019-01
4,2490,2019-01-01 00:00:00+00:00,iceland,<NA>,fishing vessels,1000 - 4999 gt,0,0.000935,0.000007,0.002964,...,5.685000e-07,6.100000e-09,0.000797,0.002619,0.0,2.241636,82,-23.127956,66.069336,2019-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18219900,250,2019-01-31 23:59:57+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.916833,249,-20.317630,65.825250,2019-01
18219901,145,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.117709,202,-14.007736,64.786480,2019-01
18219902,931,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,3.387100,180,17.170370,60.678890,2019-01
18219903,2117,2019-01-31 23:59:58+00:00,iceland,<NA>,other activities,< 1000 gt,0,0.000807,0.000006,0.002558,...,4.907000e-07,6.400000e-09,0.001176,0.003865,0.0,1.346573,363,-23.598950,65.684410,2019-01
18219904,882,2019-01-31 23:59:58+00:00,<NA>,<NA>,unknown,<NA>,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.373756,370,11.307200,64.912735,2019-01

In [3]:
# Dans ton notebook Jupyter
import pandas as pd
path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data\ASTD_area_level3_201901.csv"

# On lit juste un petit échantillon
df_sample = pd.read_csv(path, sep=';', nrows=100)

# Affiche les informations sur les types de données de l'échantillon
print(df_sample.info())

# Regarde les premières lignes des colonnes problématiques
print(df_sample.iloc[:, [3, 5]].head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   shipid          100 non-null    int64
 1   date_time_utc   100 non-null    object
 2   flagname        0 non-null      float64
 3   iceclass        0 non-null      float64
 4   astd_cat        100 non-null    object
 5   sizegroup_gt    0 non-null      float64
 6   fuelquality     100 non-null    int64
 7   fuelcons        0 non-null      float64
 8   co              0 non-null      float64
 9   co2             0 non-null      float64
 10  so2             0 non-null      float64
 11  pm              0 non-null      float64
 12  nox             0 non-null      float64
 13  n2o             0 non-null      float64
 14  nmvoc           0 non-null      float64
 15  ch4             0 non-null      float64
 16  blackcarbon     0 non-null      float64
 17  organiccarbon   0 non-null      float64
 18  oilbilgewater   0 non-null      float64
 19  blackwater      0 non-null      float64
 20  greywater       0 non-null      float64
 21  garbage         0 non-null      float64
 22  dist_nextpoint  100 non-null    float64
 23  sec_nextpoint   100 non-null    int64
 24  longitude       100 non-null    float64
 25  latitude        100 non-null    float64
dtypes: float64(21), int64(3), object(2)
memory usage: 20.4+ KB
None
   iceclass  sizegroup_gt
0       NaN           NaN
1       NaN           NaN
2       NaN           NaN
3       NaN           NaN
4       NaN           NaN