In [1]:
import sys
import os




project_path = r"C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)

import track_builder as tb

import pandas as pd
import track_builder as tb

import os
from dotenv import load_dotenv

load_dotenv()

saving_path = os.getenv("SAVING")
output_path = os.path.join(saving_path, "tracks")
os.makedirs(output_path, exist_ok=True)

BASE_PATH = r"C:\Users\lamin\Documents\maitrise\ASTD\data"
YEAR      = 2019

MONTHS_TO_LOAD = [1, 2, 3]

USECOLS   = "default"
SAMPLING  = [0, -1]

COLS_REQUIRED = [
    "shipid",
    "date_time_utc",
    "latitude",
    "longitude",
    "astd_cat",
    "flagname",
    "iceclass",
    "sizegroup_gt"
]

In [2]:
df_parquet_file = output_path_df = os.path.join(saving_path, "dataframes3month_astd_data.parquet")

if os.path.exists(df_parquet_file):
    df = pd.read_parquet(df_parquet_file)
else:
    df = tb.load_astd_monthly(
        BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
        usecols=USECOLS, sampling=None, remove_nan_rows=COLS_REQUIRED
    )

    output_path_df = os.path.join(saving_path, "dataframes")
    df.to_parquet(output_path_df + "3month_astd_data2.parquet", index=False)

In [3]:
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,1645,2019-01-01 00:00:00+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,0.731465,361,-23.703033,64.896217
1,162,2019-01-01 00:00:00+00:00,Iceland,NaN,Unknown,NaN,2.242847,209,-21.827280,64.134209
2,3619,2019-01-01 00:00:00+00:00,Norway,NaN,Other activities,1000 - 4999 GT,491.440918,369,14.545295,68.205574
3,2490,2019-01-01 00:00:00+00:00,Iceland,NaN,Fishing vessels,1000 - 4999 GT,2.241636,82,-23.127956,66.069336
4,2778,2019-01-01 00:00:01+00:00,Cyprus,NaN,Other activities,1000 - 4999 GT,1.755199,539,25.198217,60.221077
...,...,...,...,...,...,...,...,...,...,...
31410007,20554,2019-03-31 23:59:57+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,1981.756470,370,6.620860,63.038258
31410008,5018,2019-03-31 23:59:57+00:00,Liberia,FS Ice Class II,Refrigerated cargo ships,10000 - 24999,2.131150,540,-6.841878,62.049644
31410009,1998,2019-03-31 23:59:57+00:00,Iceland,NaN,Passenger ships,< 1000 GT,3.325421,281,-22.725639,65.078285
31410010,1008,2019-03-31 23:59:57+00:00,Sweden,NaN,Unknown,NaN,1159.941895,279,17.816191,60.908493
31410011,2277,2019-03-31 23:59:58+00:00,Faeroe Islands,NaN,Fishing vessels,< 1000 GT,1746.223877,360,-5.327251,62.258442

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31410012 entries, 0 to 31410011
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   shipid          int32
 1   date_time_utc   datetime64[ns, UTC]
 2   flagname        object
 3   iceclass        category
 4   astd_cat        category
 5   sizegroup_gt    category
 6   dist_nextpoint  float32
 7   sec_nextpoint   int32
 8   longitude       float32
 9   latitude        float32
dtypes: category(3), datetime64[ns, UTC](1), float32(3), int32(2), object(1)
memory usage: 1.1+ GB

In [5]:
#preprocessing

df_preprocessing = tb.remove_unrealistic_points(df)

Calcul des profils de vitesse...

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:332: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  out = (ship_means.groupby('astd_cat')
C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:140: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  valid_bwd = valid_fwd.shift(1).fillna(False) & is_same_ship_prev

Nettoyage terminé : 2070789 points 'fantômes' ou aberrants supprimés.

In [6]:
df_preprocessing

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
283,27,2019-01-01 00:01:12+00:00,Finland,NaN,Unknown,NaN,0.667353,450,21.368603,60.406395
1852,27,2019-01-01 00:08:42+00:00,Finland,NaN,Unknown,NaN,0.918571,370,21.368597,60.406391
3106,27,2019-01-01 00:14:52+00:00,Finland,NaN,Unknown,NaN,2.480580,370,21.368580,60.406391
4623,27,2019-01-01 00:21:03+00:00,Finland,NaN,Unknown,NaN,2.140826,370,21.368618,60.406403
6204,27,2019-01-01 00:27:13+00:00,Finland,NaN,Unknown,NaN,1.633218,370,21.368584,60.406410
...,...,...,...,...,...,...,...,...,...,...
7170338,24930,2019-01-21 13:49:57+00:00,Netherlands,NaN,Fishing vessels,< 1000 GT,3.985830,749,165.043213,71.685928
7173328,24930,2019-01-21 14:02:25+00:00,Netherlands,NaN,Fishing vessels,< 1000 GT,3.726456,421,165.043274,71.685959
7175180,24930,2019-01-21 14:09:26+00:00,Netherlands,NaN,Fishing vessels,< 1000 GT,3.726456,599,165.043228,71.685928
7177796,24930,2019-01-21 14:19:25+00:00,Netherlands,NaN,Fishing vessels,< 1000 GT,3.347890,420,165.043274,71.685959
7179379,24930,2019-01-21 14:26:25+00:00,Netherlands,NaN,Fishing vessels,< 1000 GT,NaN,0,165.043365,71.685951

In [7]:
df_preprocessing.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29339223 entries, 283 to 7179379
Data columns (total 10 columns):
 #   Column          Dtype
---  ------          -----
 0   shipid          int32
 1   date_time_utc   datetime64[ns, UTC]
 2   flagname        object
 3   iceclass        category
 4   astd_cat        category
 5   sizegroup_gt    category
 6   dist_nextpoint  float32
 7   sec_nextpoint   int32
 8   longitude       float32
 9   latitude        float32
dtypes: category(3), datetime64[ns, UTC](1), float32(3), int32(2), object(1)
memory usage: 1.3+ GB

In [8]:
# verify if .parquet file exists, if yes load it, else build tracks and save it
parquet_file_path = os.path.join(output_path, "tracks_2019_Q1.parquet")

if os.path.exists(parquet_file_path):
    tracks = pd.read_parquet(parquet_file_path)
else:
    tracks = tb.build_ship_tracks(df,
                                  max_time_gap_hours=25,
                                  max_distance_km=400,
                                  min_track_length=1,
                                  matching_strategy="balanced",
                                  )
    tracks.to_parquet(parquet_file_path)

tracks

         month  segment_id  track_id
0      2019-01        1645         1
1      2019-01         162         2
2      2019-01        3619         3
3      2019-01        2490         4
4      2019-01        2778         5
...        ...         ...       ...
13241  2019-03       20532     12731
13242  2019-03       20626     12732
13243  2019-03       20619     12733
13244  2019-03       20546     12734
13245  2019-03       20629     12735

[13246 rows x 3 columns]

In [9]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13246 entries, 0 to 13245
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   month       13246 non-null  object
 1   segment_id  13246 non-null  int64
 2   track_id    13246 non-null  int64
dtypes: int64(2), object(1)
memory usage: 310.6+ KB

In [10]:
tb.get_track_statistics(tracks, df)

{'n_tracks': 12735,
 'n_segments': 13246,
 'avg_length': 1.0401256380054966,
 'max_length': 3,
 'lengths': track_id
 1        1
 2        1
 3        1
 4        1
 5        1
         ..
 12731    1
 12732    1
 12733    1
 12734    1
 12735    1
 Length: 12735, dtype: int64,
 'by_month': month
 2019-01    6941
 2019-02    3830
 2019-03    2475
 dtype: int64,
 'by_ship_type': astd_cat
 bulk carriers                     2390
 fishing vessels                   2254
 general cargo ships               1665
 other activities                  1481
 container ships                   1310
 chemical tankers                   775
 unknown                            637
 passenger ships                    603
 ro-ro cargo ships                  501
 crude oil tankers                  417
 offshore supply ships              355
 gas tankers                        233
 refrigerated cargo ships           216
 oil product tankers                179
 cruise ships                       126
 other service offshore vessels     104
 Name: count, dtype: int64}

In [11]:
# tracks that span at least 2 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 2].index

print("Number of tracks spanning at least 2 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 2 months: 449

      month  segment_id  track_id
19  2019-01        1541        20
20  2019-02        1418        20
27  2019-01         171        27
28  2019-02         161        27
29  2019-03         262        27
37  2019-01        9019        35
38  2019-02        5670        35
40  2019-01        5901        37
41  2019-02        4573        37
60  2019-01         693        56

In [12]:
# tracks that span at least 3 months
month_counts = tracks.groupby("track_id")["month"].nunique()
multi_month_ids = month_counts[month_counts >= 3].index

print("Number of tracks spanning at least 3 months:", len(multi_month_ids))
tracks[tracks["track_id"].isin(multi_month_ids)].head(10)

Number of tracks spanning at least 3 months: 62

      month  segment_id  track_id
27  2019-01         171        27
28  2019-02         161        27
29  2019-03         262        27
60  2019-01         693        56
61  2019-02         708        56
62  2019-03         740        56
69  2019-01         660        63
70  2019-02         672        63
71  2019-03         703        63
87  2019-01        4490        77

In [13]:

work = tb.build_light_multi_track_data(track_table=tracks, track_sampling=20, positions_df=df_preprocessing, n_tracks_length=3,
                                       base_path=BASE_PATH, chunksize=500_000, progress=True, point_stride=10,
                                       random_state=42)

fig = tb.plot_ship_tracks(
    work,
    color_by="track_id",
    color_mode="categorical",
    show_points=True,
    map_style="open-street-map",
    title="Tracks (light multi-track sample)",
)
fig.update_layout(showlegend=False)
fig.show()

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\io\astd_loader.py:432: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.iloc[::point_stride])

In [14]:
df_track_6348 = tb.load_track_data(track_id=6348, track_table=tracks, base_path=BASE_PATH, chunksize=500000)
track = 6348
fig_test = tb.plot_individual_track(
                track,
                tracks,
                df_track_6348,
                show_segments=True,
                map_style="open-street-map",
                title=f"Track {track} ",
            )

fig_test.show()

c:\Users\lamin\miniconda3\envs\torch-gpu\Lib\site-packages\tqdm\auto.py:21: TqdmWarning:

IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

Loading positions for track 6348: 100%|██████████| 2/2 [00:59<00:00, 29.79s/it]

Calcul des profils de vitesse...

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:332: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:140: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [15]:
df_track_5831 = tb.load_track_data(track_id=5831, track_table=tracks, base_path=BASE_PATH, chunksize=500000)
track = 5831
fig_test2 = tb.plot_individual_track(
                track,
                tracks,
                df_track_5831,
                show_segments=True,
                map_style="open-street-map",
                title=f"Track {track} ",
            )

fig_test2.show()

Loading positions for track 5831: 100%|██████████| 2/2 [01:00<00:00, 30.15s/it]

Calcul des profils de vitesse...
Nettoyage terminé : 51 points 'fantômes' ou aberrants supprimés.

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:332: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:140: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

In [16]:
df_track_27 = tb.load_track_data(track_id=27, track_table=tracks, base_path=BASE_PATH, chunksize=500000)
track = 27
fig_test3 = tb.plot_individual_track(
                track,
                tracks,
                df_track_27,
                show_segments=True,
                map_style="open-street-map",
                title=f"Track {track} ",
            )

fig_test3.show()

Loading positions for track 27: 100%|██████████| 3/3 [01:33<00:00, 31.29s/it]

Calcul des profils de vitesse...

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:332: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:140: FutureWarning:

Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`

Nettoyage terminé : 9039 points 'fantômes' ou aberrants supprimés.