In [1]:
import sys
import os




project_path = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)

import track_builder as tb

YEAR      = 2019
# At least 5 months (adjust as needed)
MONTHS_TO_LOAD = [5, 6]

# Keep it lightweight: first and last day of each month + quality filter
USECOLS   = "default"
SAMPLING  = [0, -1]
QUAL_MIN  = 60

BASE_PATH = r"C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\data"
df = tb.load_astd_monthly(
    BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
    usecols=USECOLS, sampling=SAMPLING, quality_threshold_minutes=QUAL_MIN
)

# Construire les tracks + récupérer les logs
tracks, logs = tb.build_ship_tracks(
    df,
    max_time_gap_hours=48,
    max_distance_km=600,
    min_track_length=2,
    matching_strategy="balanced",
    return_logs=True,
)

# Candidats pour un segment
# cands, clog = tb.find_track_candidates("ship_12345", "2019-07", df, top_n=5, return_logs=True)

# Stats
# stats = tb.get_track_statistics(tracks, df)
# print(stats["n_tracks"], stats["avg_length"], stats["max_length"])

Loading ASTD CSVs:   0%|          | 0/2 [00:00<?, ?it/s]

C:\Users\lamin\OneDrive\Documents\Maitrise en info Canada\ASTD project\TrackBuilder\track_builder\core\io_helpers.py:139: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  tmp["_month"] = tmp["date_time_utc"].dt.to_period("M").astype(str)

Data sample after cleaning:
  Date range: 2019-05-01 00:00:00+00:00 to 2019-06-30 23:59:57+00:00
  Ship types: ['unknown' 'fishing vessels' 'bulk carriers' 'general cargo ships'
 'other activities' 'chemical tankers' 'crude oil tankers'
 'passenger ships' 'ro-ro cargo ships' 'other service offshore vessels'
 'offshore supply ships' 'oil product tankers' 'gas tankers'
 'container ships' 'refrigerated cargo ships' 'cruise ships']
  Unique ships: 3888
Creating segments for 3888 unique shipids
Created 3888 segments
Sample segment: unknown|nan|nan|nan

In [2]:
logs

,match_id,from_shipid,to_shipid,from_month,to_month,stage,reason,dt_hours,distance_km_fd,implied_v_kmh
0,618→603,618.0,603.0,2019-05,2019-06,filter,time_window,720.011667,261.379150,NaN
1,618→1045,618.0,1045.0,2019-05,2019-06,filter,time_window,720.011944,683.933899,NaN
2,618→1064,618.0,1064.0,2019-05,2019-06,filter,time_window,720.013056,746.997803,NaN
3,618→600,618.0,600.0,2019-05,2019-06,filter,time_window,720.013056,63.919846,NaN
4,618→1739,618.0,1739.0,2019-05,2019-06,filter,time_window,720.013611,1295.384399,NaN
...,...,...,...,...,...,...,...,...,...,...
3698841,3540→1938,NaN,NaN,NaN,NaN,skip,already_assigned,NaN,NaN,NaN
3698842,3540→837,NaN,NaN,NaN,NaN,skip,already_assigned,NaN,NaN,NaN
3698843,3540→632,NaN,NaN,NaN,NaN,skip,already_assigned,NaN,NaN,NaN
3698844,3540→641,NaN,NaN,NaN,NaN,skip,already_assigned,NaN,NaN,NaN
3698845,3540→960,NaN,NaN,NaN,NaN,skip,already_assigned,NaN,NaN,NaN

In [55]:
stats = tb.get_track_statistics(tracks, df)
print(stats["n_tracks"], stats["avg_length"], stats["max_length"])

635 2.0 2

In [56]:
tracks.head()

     month  segment_id  track_id
0  2019-05        1877         2
1  2019-06        1883         2
2  2019-05        1885        10
3  2019-06        1933        10
4  2019-05        1837        11

In [9]:
# Candidats pour un segment
cands, clog = tb.find_track_candidates(1877, "2019-05", df, top_n=5, return_logs=True)

Data sample after cleaning:
  Date range: 2019-05-01 00:00:00+00:00 to 2019-06-30 23:59:57+00:00
  Ship types: ['unknown' 'fishing vessels' 'bulk carriers' 'general cargo ships'
 'other activities' 'chemical tankers' 'crude oil tankers'
 'passenger ships' 'ro-ro cargo ships' 'other service offshore vessels'
 'offshore supply ships' 'oil product tankers' 'gas tankers'
 'container ships' 'refrigerated cargo ships' 'cruise ships']
  Unique ships: 3888
Creating segments for 3888 unique shipids
Created 3888 segments
Sample segment: unknown|nan|nan|nan

In [10]:
cands

,month,segment_id,match_score_simple,match_score_core,distance_km_fd,implied_v_kmh,dt_hours
0,2019-06,2070,0.007439,NaN,0.060353,0.413847,0.145833
1,2019-06,1883,0.007578,NaN,0.042561,0.436520,0.097500
2,2019-06,3957,0.013326,NaN,0.079413,0.787565,0.100833
3,2019-06,1893,0.049471,NaN,0.313346,3.000125,0.104444
4,2019-06,1880,0.065830,NaN,0.379419,4.005596,0.094722

In [12]:
clog

,match_id,from_shipid,to_shipid,from_month,to_month,stage,reason,dt_hours,distance_km_fd,implied_v_kmh
0,1877→603,1877,603,2019-05,2019-06,filter,distance_window,0.091111,1600.061890,NaN
1,1877→3795,1877,3795,2019-05,2019-06,filter,distance_window,0.091389,2241.420898,NaN
2,1877→1045,1877,1045,2019-05,2019-06,filter,distance_window,0.091389,2070.852783,NaN
3,1877→1046,1877,1046,2019-05,2019-06,filter,distance_window,0.091944,2009.173462,NaN
4,1877→4556,1877,4556,2019-05,2019-06,filter,distance_window,0.092222,1453.748901,NaN
...,...,...,...,...,...,...,...,...,...,...
787,1877→2265,1877,2265,2019-05,2019-06,filter,speed_cap,3.632222,1006.874084,277.206080
788,1877→2313,1877,2313,2019-05,2019-06,filter,speed_cap,5.312222,933.960754,175.813570
789,1877→202,1877,202,2019-05,2019-06,filter,speed_cap,10.081111,815.252869,80.869347
790,1877→2743,1877,2743,2019-05,2019-06,filter,speed_cap,10.982500,924.600891,84.188563
791,1877→4102,1877,4102,2019-05,2019-06,filter,speed_cap,17.236944,918.947937,53.312694

In [11]:
# segments du track 2
t2 = tracks[tracks['track_id']==2].sort_values('month')
print(t2)

# regarder les décisions autour de 1885 (mai) -> 1933 (juin)
mask = (logs['from_shipid'] == float(1877)) | (logs['to_shipid'] == float(1883))
print(logs[mask].head(20))

     month  segment_id  track_id
0  2019-05        1877         2
1  2019-06        1883         2
        match_id  from_shipid  to_shipid from_month to_month   stage  \
412     618→1883        618.0     1883.0    2019-05  2019-06  filter
1679   1877→5628       1877.0     5628.0    2019-05  2019-06  filter
1680  1877→17343       1877.0    17343.0    2019-05  2019-06  filter
1681  1877→13931       1877.0    13931.0    2019-05  2019-06  filter
1682  1877→13442       1877.0    13442.0    2019-05  2019-06  filter
1683   1877→8970       1877.0     8970.0    2019-05  2019-06  filter
1684  1877→12866       1877.0    12866.0    2019-05  2019-06  filter
1685  1877→18618       1877.0    18618.0    2019-05  2019-06  filter
1686  1877→12939       1877.0    12939.0    2019-05  2019-06  filter
1687  1877→14042       1877.0    14042.0    2019-05  2019-06  filter
1688   1877→7951       1877.0     7951.0    2019-05  2019-06  filter
1689  1877→11005       1877.0    11005.0    2019-05  2019-06  filter
1690  1877→18141       1877.0    18141.0    2019-05  2019-06  filter
1691   1877→6887       1877.0     6887.0    2019-05  2019-06  filter
1692  1877→13407       1877.0    13407.0    2019-05  2019-06  filter
1693  1877→10957       1877.0    10957.0    2019-05  2019-06  filter
1694   1877→9530       1877.0     9530.0    2019-05  2019-06  filter
1695  1877→13979       1877.0    13979.0    2019-05  2019-06  filter
1696  1877→14431       1877.0    14431.0    2019-05  2019-06  filter
1697   1877→6060       1877.0     6060.0    2019-05  2019-06  filter

           reason    dt_hours  distance_km_fd  implied_v_kmh
412   time_window  720.018056     1485.013428            NaN
1679  time_window  696.092222     1654.024414            NaN
1680  time_window  696.097500     1708.542969            NaN
1681  time_window  696.100000     1411.392700            NaN
1682  time_window  696.100556     1641.369385            NaN
1683  time_window  696.101944     1518.781494            NaN
1684  time_window  696.102778     5451.289062            NaN
1685  time_window  696.104444     1555.787476            NaN
1686  time_window  696.105000     1440.629150            NaN
1687  time_window  696.111944     1455.005249            NaN
1688  time_window  696.113889     5360.358887            NaN
1689  time_window  696.115833     1410.473511            NaN
1690  time_window  696.121389     5822.567871            NaN
1691  time_window  696.121389     1412.026001            NaN
1692  time_window  696.123333     1708.138306            NaN
1693  time_window  696.126389       17.201334            NaN
1694  time_window  696.130556     1413.451660            NaN
1695  time_window  696.131944      114.199318            NaN
1696  time_window  696.133056       42.074726            NaN
1697  time_window  696.134167     2240.323730            NaN

In [51]:
# choose a track id to visualize
fig_track = tb.plot_individual_track(
    2,
    tracks,
    df,
    show_segments=True,                 # one polyline per segment (often = shipid)
    map_style="open-street-map",
    title=f"Track {2} – vue détaillée",
)


fig_track.show()

In [53]:
import pandas as pd
# fig_track2 en utilisant plot_ship_tracks avec df filtré 

# choisir id = 1877 (mai 2019) qui a été bien suivi et seulement le dernier jour de mai
df_1877_filtered = df[(df['shipid'] == 1877) & (df['date_time_utc'].dt.month == 5) & (df['date_time_utc'].dt.day == 31)]

# choisir le navire avec id = 2070 (juin 2019) qui a été bien suivi et seulement le premier jour de juin
df_2070_filtered = df[(df['shipid'] == 2070) & (df['date_time_utc'].dt.month == 6) & (df['date_time_utc'].dt.day == 1)]

#  concaténer les deux DataFrames
df_filtered = pd.concat([df_1877_filtered, df_2070_filtered])

fig_track2 = tb.plot_ship_tracks(
    df_filtered,
    show_points=True,
    color_by="shipid",
    title="Trajectoires des navires 1877 et 2070",
    map_style="open-street-map",
)

fig_track2.show()

In [54]:
# choisir le navire avec id = 1883 (juin 2019) qui a été bien suivi et seulement le premier jour de juin
df_1883_filtered = df[(df['shipid'] == 1883) & (df['date_time_utc'].dt.month == 6) & (df['date_time_utc'].dt.day == 1)]

df_filtered2 = pd.concat([df_1877_filtered, df_1883_filtered])

fig_track3 = tb.plot_ship_tracks(
    df_filtered2,
    show_points=True,
    color_by="shipid",
    title="Trajectoires des navires 1877 et 2070",
    map_style="open-street-map",
)

fig_track3.show()

In [24]:
# choisir le navire avec id = 1877 (mai 2019) qui a été bien suivi
df_1877 = df[(df['shipid'] == 1877) & (df['date_time_utc'].dt.month == 5)]

fig_1877 = tb.plot_ship_tracks(
    df_1877,
    show_points=True,
    color_by="shipid",
    map_style="open-street-map",
    date_from="2019-05-31",
)

df_1877.head(1)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
1,1877,2019-05-01 00:00:01+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,1119.830688,310,-22.486521,64.416367

In [25]:
fig_1877.show()

In [47]:
# choisir le navire avec id = 2070 (juin 2019) qui a été bien suivi
df_2070 = df[(df['shipid'] == 2070) & (df['date_time_utc'].dt.month == 6)]

fig_2070 = tb.plot_ship_tracks(
    df_2070,
    show_points=True,
    color_by="shipid",
    map_style="open-street-map",
    date_to="2019-06-01 23:59:59", #ajouté l'heure
)

df_2070.head(1)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
475332,2070,2019-06-01 00:03:18+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,1.542593,121,-22.420359,63.839466

In [48]:
fig_2070.show()

In [49]:
# choisir le navire avec id = 2070 (juin 2019) qui a été bien suivi
df_1883 = df[(df['shipid'] == 1883) & (df['date_time_utc'].dt.month == 6)]

fig_1883 = tb.plot_ship_tracks(
    df_1883,
    show_points=True,
    color_by="shipid",
    map_style="open-street-map",
    date_to="2019-06-01 23:59:59", #ajouté l'heure
)

df_1883.head(1)

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
474943,1883,2019-06-01 00:00:24+00:00,Iceland,NaN,Fishing vessels,< 1000 GT,0.380528,39,-22.419182,63.839184

In [50]:
fig_1883.show()