In [ ]:
import sys
import os

project_path = r"C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder"
if project_path not in sys.path:
    sys.path.append(project_path)
import track_builder as tb


BASE_PATH = r"C:\Users\lamin\Documents\maitrise\ASTD\data"
YEAR      = 2019

MONTHS_TO_LOAD = [1, 2, 3, 4]

USECOLS   = "default"
SAMPLING  = [0, -1]

COLS_REQUIRED = [
    "shipid",
    "date_time_utc",
    "latitude",
    "longitude",
    "astd_cat",
    "flagname",
    "iceclass",
    "sizegroup_gt"
]

In [ ]:
df = tb.load_astd_monthly(
    BASE_PATH, YEAR, months=MONTHS_TO_LOAD, progress=True,
    usecols=USECOLS, sampling=None, remove_nan_rows=COLS_REQUIRED
)
    
df

,shipid,date_time_utc,flagname,iceclass,astd_cat,sizegroup_gt,dist_nextpoint,sec_nextpoint,longitude,latitude
0,5966,2019-01-01 00:00:02+00:00,Russia,FS Ice Class 1A,General cargo ships,10000 - 24999,616.758301,971,72.985146,73.034294
1,3994,2019-01-01 00:00:02+00:00,Norway,FS Ice Class 1C,Offshore supply ships,1000 - 4999 GT,8.541162,371,5.850370,62.335602
2,3768,2019-01-01 00:00:02+00:00,Netherlands,FS Ice Class 1C,Other service offshore vessels,10000 - 24999,0.000000,718,7.734500,63.110500
3,1892,2019-01-01 00:00:04+00:00,Russia,FS Ice Class 1C,Fishing vessels,< 1000 GT,1.028629,540,29.700306,70.626442
4,3009,2019-01-01 00:00:04+00:00,Norway,FS Ice Class 1C,Fishing vessels,< 1000 GT,1945.192749,371,25.147583,70.990837
...,...,...,...,...,...,...,...,...,...,...
14305839,6556,2019-04-30 23:59:54+00:00,Cyprus,FS Ice Class 1A,Container ships,10000 - 24999,1226.629028,210,23.807863,65.276199
14305840,12580,2019-04-30 23:59:55+00:00,Cyprus,FS Ice Class 1A,General cargo ships,1000 - 4999 GT,4.734151,360,21.275877,64.670944
14305841,15295,2019-04-30 23:59:58+00:00,Antigua & Barbuda,FS Ice Class 1A,General cargo ships,5000 - 9999 GT,284.300659,41,20.490366,63.116634
14305842,14711,2019-04-30 23:59:58+00:00,Barbados,FS Ice Class II,General cargo ships,1000 - 4999 GT,1.162097,360,9.639557,63.816971
14305843,7249,2019-04-30 23:59:58+00:00,Antigua & Barbuda,FS Ice Class II,Container ships,5000 - 9999 GT,3003.786621,360,7.603065,63.312439

In [ ]:

target_segment_id = 1792   
current_month = '2019-01'   

candidates_df = tb.find_track_candidates(
    segment_id=target_segment_id,
    month=current_month,
    astd_data=df_for_track,
    
    max_time_gap_hours=25,
    max_distance_km=400,
    matching_strategy="balanced",  
    
    w_time=0.4,
    w_dist=0.4,
    w_speed=0.2,
    
    gap_days_no_penalty=3.0,  
    gap_penalty_per_day=0.05,
    
    top_n=5,
    return_logs=False
)

print(f"--- Top Candidates for Segment {target_segment_id} ---")

display(candidates_df)

Data after cleaning:
  Date range: 2019-01-01 00:00:02+00:00 to 2019-04-30 23:59:58+00:00
  Ship types: ['other service offshore vessels' 'offshore supply ships'
 'general cargo ships' 'passenger ships' 'fishing vessels' 'bulk carriers'
 'other activities' 'ro-ro cargo ships' 'cruise ships'
 'refrigerated cargo ships' 'chemical tankers' 'container ships'
 'gas tankers' 'crude oil tankers' 'oil product tankers']
  Unique ships: 3367

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:230: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  df['period_month'] = df['date_time_utc'].dt.to_period('M')

Creating segments for 4106 unique ship-months (segments)...
Successfully created 4106 monthly segments.
Sample segment: fishing vessels|russia|fs ice class 1c|< 1000 gt in 2019-04
--- Top Candidates for Segment 1792 ---

C:\Users\lamin\Documents\maitrise\ASTD\TrackBuilder\track_builder\core\track_helpers.py:382: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  out = (ship_means.groupby('astd_cat')

,month,segment_id,match_score_simple,distance_km_fd,implied_v_kmh,dt_hours
0,2019-02,2834,0.310436,56.525143,6.150351,9.190556
1,2019-02,2970,0.356587,72.461563,7.823345,9.262222
2,2019-02,2814,0.357536,72.825340,7.937607,9.174722
3,2019-02,3008,0.360771,73.944183,8.063462,9.170278
4,2019-02,1793,0.371126,77.510460,8.324761,9.310833